# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
default_platform(:android)

platform :android do

  desc "Deploy a new version to the FireBase"
  lane :deploy do
    begin

      build_android_app(
        # archive_path: "../build/app/outputs/flutter-apk/app-release.apk",
        gradle(
        task: "assemble",
        flavor: "WorldDomination",
        build_type: "Release"
      )
    )
    firebase_app_distribution(
             app: "1:49131233725:android:2ef7ee2aad6218c0b632d4",
             firebase_cli_token: "1//0gumtx_jEzWk4CgYIARAAGBASNwF-L9IrLRiQvHpFgzZb73namLYVv1yr1s1fvVVyyHThEQEoofEDPdXbVMJMq4pQBxQa0cRB5z4",
             groups: "test",
             apk_path:"../build/app/outputs/flutter-apk/app-release.apk",
             release_notes: "Lots of amazing new features to test out !")
    end
  end
end